# a= 10
# b = 0
# try:
#     print(a/b)
#     try:
#         print("This is inner try block")
#     except Exception:
#         print("General Exception")
#     finally:
#         print("Inside outer finally block")

# except ZeroDivisionError:
#     print("Division by 0")
# finally:
#     print("Inside outer finally block")

# a = 10
# b = 0
# try:
#     print("this is outer try block")
#     try: 
#         print(a/b)
#     except ZeroDivisionError:
#         print("Division by 0")
#     finally:
#         print("inside inner finally block")

# except Exception:
#     print("General Exception")
# finally:
#     print("Inside outer finally block")

# a = 10
# b = 0
# try:
#     print("this is outer try block")
#     try:
#         print(a/b)
#     except KeyError:
#         print("Key error")
#     finally:
#         print("inside inner finally block")

# except ZeroDivisionError:
#     print("Division by 0")
# finally:
#     print("Inside outer finally block")
    

